#!/bin/bash

# UpStage Post-Installation script
# This script is meant to create and start an UpStage server once the
# system has been installed
# Author:  Paul Rohrlach (aut.upstage.team@gmail.com)
# Created: 08/10/2010
# Revised: 09/11/2010
# Edited by Heath Behrens on 09/04/2011
# removed call to upstage-admin start 8081. As it assumes you create a server called 8081.

clear
echo "**********************************************"
echo "*           Welcome to UpStage!              *"
echo "**********************************************"
echo 
echo "Authorizing UpStage..."
sudo chmod +x /usr/local/upstage/*
echo
echo "Setting up automated archiver..."
sudo chmod +x /etc/cron.weekly/upstage-backup
echo
echo "Creating links..."
sudo ln -s /usr/local/upstage/* /usr/local/bin/
sudo ln -s /etc/cron.weekly/upstage-backup /usr/local/bin/
echo
echo "Asking to create a server..."
sudo upstage-admin create
echo
echo "Set up complete! Thank you for using UpStage, the venue for online cyberformance."
