#!/bin/bash
#
#
# Author: Heath Behrens (AUT UpStage Development Team)
# Date: 10/04/2011

echo "Cleaning up."
echo "###############################################"
echo ""
echo "Removing /usr/local/etc/upstage/"
rm -r /usr/local/etc/upstage/
echo "Removing /var/local/run/upstage/"
rm -r /var/local/run/upstage/
echo "Removing /var/local/log/upstage/"
rm -r /var/local/log/upstage/
echo "Removing /usr/local/upstage/"
rm -r /usr/local/upstage/
echo "Removing /usr/local/bin/upstage"
rm -r /usr/local/bin/upstage
echo "Removing /usr/local/share/upstage/"
rm -r /usr/local/share/upstage/
echo "Removing /etc/cron.weekly/upstage-backup.sh"
rm /etc/cron.weekly/upstage-backup.sh
echo ""
echo "Thank you for using UpStage!"
echo "###############################################"