#!/bin/bash
#
#
# Author: Heath Behrens (AUT UpStage Development Team)
# Date: 10/04/2011

echo "######################################################################"
echo "Killing processes"
#find the process id's associated with upstage-server
export out=`ps ux | awk '/upstage-server/ && !/awk/ {print $2}'`
#loop through the processes and kill each one.
echo "Processes found."
for pid in $out
do
    	echo "Stopping $pid"
	kill $pid
	echo "$pid stopped."
done
echo ""
echo "Complete!"
echo "######################################################################"
