		</div>
		
		<div id="footer">
			<!-- PR (09/11/2010) Thought this was a more usable place to put version info -->
			<!-- Mohammed Al-Timimi (9/06/2011) - Moved because it was placed so very badly -->
			
			<!-- TODO dynamically insert version number -->
			<p style="font-size:9px;font-weight:bold;color:#bbb;font-family:Verdana,Arial,'Bitstream Vera Sans',Helvetica,sans-serif">UpStage version 2.4.2.video-hack.1 &mdash; <a href="https://github.com/foobarlab/UpStage" style="color:#bbb;text-decoration:none"><i class="icon-github icon-large"></i> Fork me on GitHub</a></p>	
		</div>
		<div id="status" style="display:none;">
		</div>
	</div>
	
</body>
</html>
