		<div id ="workshopnav">
			<ul>
				<li>Workshop:</li>
				<li><a href="javascript:navStageWorkshop();" id="stagelink">Create/Edit Stage</a></li>
				<li><a href="javascript:navMediaUpWorkshop();" id="mediauploadlink">Upload Media</a></li>
				<li><a href="javascript:navMediaEditWorkshop();" id="mediaeditlink" >Edit/View Media</a></li>
				<li><a href="javascript:navUserPage();" id="userlink" >Edit Players</a></li>
				%(nav)s
			</ul>
		</div>
