		<div id ="workshopnav">
			<ul>
				<li>Workshop:</li>
				<li><a href="javascript:navStageWorkshop();" id="stagelink">Create/Edit Stage</a></li>
				<li><a href="javascript:navMediaUpWorkshop();" id="mediauploadlink">Add Media</a></li>
				<!--
				<li><a href="javascript:navMediaEditWorkshop();" id="mediaeditlink" >Edit/View Media (old)</a></li>
				-->
				<li><a href="javascript:navMediaEdit2Workshop();" id="mediaedit2link" >Edit/View Media</a></li>
				<li><a href="javascript:navUserPage();" id="userlink" >Edit Players</a></li>
				%(nav)s
			</ul>
		</div>
