<object width="200px" height="200px" scale="showAll"
  classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" 
  codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" 
  style="z-index:0"
 >
 <param name="movie" value="%(attr:url)s" />
 <param name="quality" value="high" />
 <param name="bgcolor" value="#ffffff" />
 <param name="wmode" value="opaque" />
 <embed src="%(attr:url)s" 
   width="200px" height="200px" scale="showAll" 
   type="application/x-shockwave-flash" 
   allowScriptAccess="sameDomain" 
   wmode="opaque"
   pluginspage="http://www.macromedia.com/go/getflashplayer" 
  />
</object>
