<p>
	Messages for UpStage users:dddd</p>
<p>
	We are now preparing for the 121212 UpStage Festival of Cyberformance, so there is now a lot of activity on this server. Please remember that all the media here is under a Creative Commons licence (details) - we ask that you respect others&#39; media and do not delete or edit (e.g. change voices) media that is not your own.</p>
<p>
	121212 Schedule</p>
<p>
	- asking for preferred times</p>
<p>
	121212 open rehearsals</p>
<p>
	- please invite other aritsts and 121212 volunteers to attend a rehearsal so that you have a test audience &amp; some feedback to help guide the development of your show - even if you are remounting, it&#39;s a good idea to have a run with an audience.</p>
